name: Deploy interactive API documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Build site
        run: |
          ruby scripts/build-openapi-json.rb /docs/openapi.yaml docs/openapi.json

          mkdir -p _site

          cp /docs/index.html _site/index.html
          cp /docs/openapi.yaml _site/openapi.yaml
          cp docs/openapi.json _site/openapi.json

      - name: Debug output
        run: |
          ls -R _site

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: _site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5